// <auto-generated />
namespace TwitterClone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Followees_Followers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Followees_Followers));
        
        string IMigrationMetadata.Id
        {
            get { return "201505072247433_Followees_Followers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
